---
ID: "9fe786b1-7421-4e17-98cc-a8d3e37b78e7"
Parent: "d89463c9-06db-435e-afcd-f535075fd1ab"
Template: "d89463c9-06db-435e-afcd-f535075fd1ab"
Path: /sitecore/templates/Project/Showcase/Component/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170419T104343Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
