---
ID: "8cc6a4fb-d849-4e3c-ae3d-9a24568a5ad2"
Parent: "fa8de862-a0f9-4a10-a369-2b28caac26ad"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Showcase/int/Presentation/Rendering Variants/Media Link/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160929T081202Z
    - ID: "90294353-706a-431c-b855-cd245824d9fa"
      Hint: LinkField
      Value: File
    - ID: "e1d5adba-8348-4127-9bb6-455936653839"
      Hint: CssClass
      Value: "file-type-icon-media-link"
