---
ID: "b56a6929-f03f-437f-a81e-d08f85b04e94"
Parent: "b5e5c057-c21b-419a-96b9-34be3313d8d4"
Template: "efafbbf5-01a0-46d3-9f7b-e71763e7f221"
Path: /sitecore/content/Showcase/int/Settings/Social Media Groups/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160929T081200Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
