---
ID: "d66d63cd-d70a-4e25-b1b0-874fb482be3a"
Parent: "89d58e0e-588e-49f4-a899-380158bde0ee"
Template: "a4c1e965-faf4-45ca-b112-050fa3161783"
Path: /sitecore/content/Showcase/int/home/components/security
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 1244
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Security
  Versions:
  - Version: 1
    Fields:
    - ID: "1ab993c6-6e09-4367-aaf2-9372b017910b"
      Hint: Title
      Value: Security
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161013T112811Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
    - ID: "6e8f1561-3bb0-4ba5-bfc1-18a32abab6f8"
      Hint: SummaryTitle
      Value: Security
