---
ID: "0abeb632-5701-4e37-82be-a33ef841ad70"
Parent: "1b9bdc53-3d91-41bf-a7ea-220d8f8ff9fb"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Showcase/int/Presentation/Rendering Variants/Promo/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160929T081158Z
