---
ID: "fc13847d-a431-4a37-aa7e-0e330c3d6e9d"
Parent: "88cd22fd-94d2-4919-a49a-6e9f117d2c40"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Showcase/int/Presentation/Rendering Variants/Search Results/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160929T081207Z
